name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=12.0

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: msbuild
    # - name: Pack
    #  run: dotnet pack --no-restore
    - name: Publish Eternity
      run: dotnet nuget push **/*.nupkg -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json -n true
      env:
         NUGET_TOKEN: ${{secrets.PUBLIC_NUGET_TOKEN}}

    - name: Publish Eternity Proget
      run: dotnet nuget push **/*.nupkg -k ${NUGET_KEY} -s ${NUGET_SOURCE} -n true
      env:
         NUGET_SOURCE: ${{secrets.PROGET_NUGET}}
         NUGET_KEY: ${{secrets.PROGET_NUGET_TOKEN}}  


    - name: Create tag
      uses: actions/github-script@v6
      with:
        script: |
          const { NBGV_SemVer2 } = process.env
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/v${NBGV_SemVer2}`,
            sha: context.sha
          })  
